FROM nginx

RUN apt update && apt install openssl

# Move our nginx config file to the container for use.
COPY nginx.conf /etc/nginx/nginx.conf

# Create self-signed SSL
RUN mkdir /ssl
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj "/C=US/ST=MA/L=Wilbraham/O=Cre8tiv/CN=localhost" -keyout /ssl/private_key.key -out /ssl/cert.crt